// <auto-generated />
using System;
using KAdanceAPI.data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KAdanceAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("KAdanceAPI.models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("KAdanceAPI.models.DanceClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeEnd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeStart")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Trainer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DanceClasses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DayOfWeek = "Понеділок",
                            Name = "Пілатес",
                            TimeEnd = "10:00",
                            TimeStart = "09:00",
                            Trainer = "Ксенія"
                        },
                        new
                        {
                            Id = 2,
                            DayOfWeek = "Понеділок",
                            Name = "Стретчинг",
                            TimeEnd = "11:00",
                            TimeStart = "10:00",
                            Trainer = "Ксенія"
                        },
                        new
                        {
                            Id = 3,
                            DayOfWeek = "Понеділок",
                            Name = "Айро фітнес",
                            TimeEnd = "12:00",
                            TimeStart = "11:00",
                            Trainer = "Ксенія"
                        },
                        new
                        {
                            Id = 4,
                            DayOfWeek = "Понеділок",
                            Name = "Контемпорарі 8-11 років",
                            TimeEnd = "17:00",
                            TimeStart = "15:30",
                            Trainer = "Ксенія"
                        },
                        new
                        {
                            Id = 5,
                            DayOfWeek = "Понеділок",
                            Name = "Контемпорарі 12-16 років",
                            TimeEnd = "18:30",
                            TimeStart = "17:00",
                            Trainer = "Ксенія"
                        },
                        new
                        {
                            Id = 6,
                            DayOfWeek = "Понеділок",
                            Name = "Пілатес",
                            TimeEnd = "20:00",
                            TimeStart = "19:00",
                            Trainer = "Ксенія"
                        },
                        new
                        {
                            Id = 7,
                            DayOfWeek = "Понеділок",
                            Name = "Стретчинг",
                            TimeEnd = "21:00",
                            TimeStart = "20:00",
                            Trainer = "Ксенія"
                        },
                        new
                        {
                            Id = 8,
                            DayOfWeek = "Вівторок",
                            Name = "Пілатес+стретчинг",
                            TimeEnd = "11:00",
                            TimeStart = "10:00",
                            Trainer = "Ксенія"
                        },
                        new
                        {
                            Id = 9,
                            DayOfWeek = "Вівторок",
                            Name = "Контемпорарі",
                            TimeEnd = "12:00",
                            TimeStart = "11:00",
                            Trainer = "Ксенія"
                        },
                        new
                        {
                            Id = 10,
                            DayOfWeek = "Вівторок",
                            Name = "Флай стретчинг",
                            TimeEnd = "13:00",
                            TimeStart = "12:00",
                            Trainer = "Ксенія"
                        },
                        new
                        {
                            Id = 11,
                            DayOfWeek = "Вівторок",
                            Name = "ЛФК+акробатика 8-13 років",
                            TimeEnd = "18:00",
                            TimeStart = "17:00",
                            Trainer = "Ксенія"
                        },
                        new
                        {
                            Id = 12,
                            DayOfWeek = "Вівторок",
                            Name = "Гімнастика+ритміка 3-5 років",
                            TimeEnd = "19:00",
                            TimeStart = "18:00",
                            Trainer = "Ольга"
                        },
                        new
                        {
                            Id = 13,
                            DayOfWeek = "Вівторок",
                            Name = "Релакс стретчинг",
                            TimeEnd = "20:00",
                            TimeStart = "19:00",
                            Trainer = "Ольга"
                        },
                        new
                        {
                            Id = 14,
                            DayOfWeek = "Вівторок",
                            Name = "Барре",
                            TimeEnd = "21:00",
                            TimeStart = "20:00",
                            Trainer = "Ольга"
                        },
                        new
                        {
                            Id = 15,
                            DayOfWeek = "Середа",
                            Name = "Пілатес",
                            TimeEnd = "10:00",
                            TimeStart = "09:00",
                            Trainer = "Ксенія"
                        },
                        new
                        {
                            Id = 16,
                            DayOfWeek = "Середа",
                            Name = "Стретчинг",
                            TimeEnd = "11:00",
                            TimeStart = "10:00",
                            Trainer = "Ксенія"
                        },
                        new
                        {
                            Id = 17,
                            DayOfWeek = "Середа",
                            Name = "Айро фітнес",
                            TimeEnd = "12:00",
                            TimeStart = "11:00",
                            Trainer = "Ксенія"
                        },
                        new
                        {
                            Id = 18,
                            DayOfWeek = "Середа",
                            Name = "Контемпорарі 8-11 років",
                            TimeEnd = "17:00",
                            TimeStart = "15:30",
                            Trainer = "Ксенія"
                        },
                        new
                        {
                            Id = 19,
                            DayOfWeek = "Середа",
                            Name = "Контемпорарі 12-16 років",
                            TimeEnd = "18:30",
                            TimeStart = "17:00",
                            Trainer = "Ксенія"
                        },
                        new
                        {
                            Id = 20,
                            DayOfWeek = "Середа",
                            Name = "Пілатес",
                            TimeEnd = "20:00",
                            TimeStart = "19:00",
                            Trainer = "Ксенія"
                        },
                        new
                        {
                            Id = 21,
                            DayOfWeek = "Середа",
                            Name = "Стретчинг",
                            TimeEnd = "21:00",
                            TimeStart = "20:00",
                            Trainer = "Ксенія"
                        },
                        new
                        {
                            Id = 22,
                            DayOfWeek = "Четвер",
                            Name = "Пілатес+стретчинг",
                            TimeEnd = "11:00",
                            TimeStart = "10:00",
                            Trainer = "Ксенія"
                        },
                        new
                        {
                            Id = 23,
                            DayOfWeek = "Четвер",
                            Name = "Контемпорарі",
                            TimeEnd = "12:00",
                            TimeStart = "11:00",
                            Trainer = "Ксенія"
                        },
                        new
                        {
                            Id = 24,
                            DayOfWeek = "Четвер",
                            Name = "Флай стретчинг",
                            TimeEnd = "13:00",
                            TimeStart = "12:00",
                            Trainer = "Ксенія"
                        },
                        new
                        {
                            Id = 25,
                            DayOfWeek = "Четвер",
                            Name = "ЛФК+акробатика 8-13 років",
                            TimeEnd = "17:30",
                            TimeStart = "16:30",
                            Trainer = "Ксенія"
                        },
                        new
                        {
                            Id = 26,
                            DayOfWeek = "Четвер",
                            Name = "Флай акробатика 9-14 років",
                            TimeEnd = "18:30",
                            TimeStart = "17:30",
                            Trainer = "Марія"
                        },
                        new
                        {
                            Id = 27,
                            DayOfWeek = "Четвер",
                            Name = "Флай стретчинг",
                            TimeEnd = "19:30",
                            TimeStart = "18:30",
                            Trainer = "Ксенія"
                        },
                        new
                        {
                            Id = 28,
                            DayOfWeek = "Четвер",
                            Name = "Зумба",
                            TimeEnd = "20:30",
                            TimeStart = "19:30",
                            Trainer = "Марія"
                        },
                        new
                        {
                            Id = 29,
                            DayOfWeek = "Четвер",
                            Name = "Айро фітнес",
                            TimeEnd = "21:30",
                            TimeStart = "20:30",
                            Trainer = "Марія"
                        },
                        new
                        {
                            Id = 30,
                            DayOfWeek = "П'ятниця",
                            Name = "Пілатес",
                            TimeEnd = "10:00",
                            TimeStart = "09:00",
                            Trainer = "Ксенія"
                        },
                        new
                        {
                            Id = 31,
                            DayOfWeek = "П'ятниця",
                            Name = "МФР стретчинг",
                            TimeEnd = "11:00",
                            TimeStart = "10:00",
                            Trainer = "Ксенія"
                        },
                        new
                        {
                            Id = 32,
                            DayOfWeek = "П'ятниця",
                            Name = "Контемпорарі 8-16 років",
                            TimeEnd = "18:00",
                            TimeStart = "17:00",
                            Trainer = "Ксенія"
                        },
                        new
                        {
                            Id = 33,
                            DayOfWeek = "П'ятниця",
                            Name = "Гімнастика+ритміка 3-5 років",
                            TimeEnd = "19:00",
                            TimeStart = "18:00",
                            Trainer = "Ольга"
                        },
                        new
                        {
                            Id = 34,
                            DayOfWeek = "П'ятниця",
                            Name = "Пілатес+стретчинг",
                            TimeEnd = "20:00",
                            TimeStart = "19:00",
                            Trainer = "Ксенія"
                        },
                        new
                        {
                            Id = 35,
                            DayOfWeek = "Субота",
                            Name = "Релакс стретчинг",
                            TimeEnd = "20:00",
                            TimeStart = "19:00",
                            Trainer = "Ольга"
                        },
                        new
                        {
                            Id = 36,
                            DayOfWeek = "Субота",
                            Name = "Барре",
                            TimeEnd = "21:00",
                            TimeStart = "20:00",
                            Trainer = "Ольга"
                        },
                        new
                        {
                            Id = 37,
                            DayOfWeek = "Неділя",
                            Name = "Флай акробатика 9-14 років",
                            TimeEnd = "18:30",
                            TimeStart = "17:30",
                            Trainer = "Марія"
                        },
                        new
                        {
                            Id = 38,
                            DayOfWeek = "Неділя",
                            Name = "Зумба",
                            TimeEnd = "19:30",
                            TimeStart = "18:30",
                            Trainer = "Марія"
                        },
                        new
                        {
                            Id = 39,
                            DayOfWeek = "Неділя",
                            Name = "Айро фітнес",
                            TimeEnd = "20:30",
                            TimeStart = "19:30",
                            Trainer = "Марія"
                        });
                });

            modelBuilder.Entity("KAdanceAPI.models.Registration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DanceClassId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("DanceClassId");

                    b.ToTable("Registrations");
                });

            modelBuilder.Entity("KAdanceAPI.models.Registration", b =>
                {
                    b.HasOne("KAdanceAPI.models.Client", "Client")
                        .WithMany("Registrations")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KAdanceAPI.models.DanceClass", "DanceClass")
                        .WithMany("Registrations")
                        .HasForeignKey("DanceClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("DanceClass");
                });

            modelBuilder.Entity("KAdanceAPI.models.Client", b =>
                {
                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("KAdanceAPI.models.DanceClass", b =>
                {
                    b.Navigation("Registrations");
                });
#pragma warning restore 612, 618
        }
    }
}
